spring:
  application:
    name: server
  cloud:
    aws:
      endpoint: https://sgp1.digitaloceanspaces.com

backend:
  certifications:
    cron: '1 */5 * * * *'
  employment:
    dataset: file:./config/employment/*.csv
  occupation:
    soc-definitions: file:./config/soc_definitions.csv
  unemployment:
    bls-url: https://api.bls.gov/publicAPI
    cron: '0 0 0 * * *'